[project]
name = "gramatico-be"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "logfire>=3.7.1",
    "openai>=1.65.4",
    "pydantic>=2.10.6",
]
